print("Welcome to the Tip Calculator")
bill = float(input("What is the total amount of the bill ? $"))
tip = int(input("What precentage of tip you would like to give ?"))
people = int(input("How many people to split the bill ?"))
total_tip = round(bill * (tip / 100), 2)
print(f"\nTotal tip amount is {total_tip}\n")
total_bill = round(bill + total_tip, 2)
print(f"Total bill amount is {total_bill}\n")
bill_per_person = round(total_bill / people, 2)
print(f"Each persom should pay :  $ {bill_per_person}")
